vich_uploader:
    db_driver: orm
    mappings:
        especes_images:
            uri_prefix: /uploads/especes
            upload_destination: '%kernel.project_dir%/public/uploads/especes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
